name: Continuous Deployment (CD)

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      PROJECT_ID: ${{ secrets.GCP_PROJECT }}
      REGION: europe-west8
      REPO: stack-exchange-repo
      PUBSUB_TOPIC: lab1-topic
      CONSUMER_IMAGE: europe-west8-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/stack-exchange-repo/stackex-consumer:latest
      PRODUCER_IMAGE: europe-west8-docker.pkg.dev/${{ secrets.GCP_PROJECT }}/stack-exchange-repo/stackex-producer:latest

    steps:
      # 2) Checkout
      - name: Checkout
        uses: actions/checkout@v4

      # 3) Auth to GCP (Service Account JSON iz GitHub Secrets)
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 4) Setup gcloud
      - name: Set up Cloud sdk
        uses: google-github-actions/setup-gcloud@v2

      # 5) Configure Docker for Artifact Registry
      - name: Configure Dockeer
        run: gcloud auth configure-docker $REGION-docker.pkg.dev --quiet

      # ----- Consumer -----
      - name: Build Consumer Docker image
        run: |
          docker build -t stackex-consumer ./consumer
          docker tag stackex-consumer $CONSUMER_IMAGE

      - name: Push Consumer Docker image
        run: docker push $CONSUMER_IMAGE

      - name: Deploy Consumer to Cloud Run (Service)
        run: |
          gcloud run deploy stackex-consumer \
            --image $CONSUMER_IMAGE \
            --region $REGION \
            --project $PROJECT_ID \
            --allow-unauthenticated

      # ----- Producer -----
      - name: Build Producer Docker image
        run: |
          docker build -t stackex-producer ./producer
          docker tag stackex-producer $PRODUCER_IMAGE

      - name: Push Producer Docker image
        run: docker push $PRODUCER_IMAGE

      - name: Deploy Producer to Cloud Run (Job)
        run: |
          gcloud run jobs deploy stackex-producer-job \
            --image $PRODUCER_IMAGE \
            --region $REGION \
            --project $PROJECT_ID \
            --set-env-vars "PROJECT_ID=$PROJECT_ID,PUBSUB_TOPIC=$PUBSUB_TOPIC"

      - name: Execute producer job
        run: |
          gcloud run jobs execute stackex-producer-job \
            --region $REGION \
            --project $PROJECT_ID
